URL_SERVICE = " https://cnt-08bce4e1-dac3-4cc0-b6ec-e183c6963713.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users"
KITS_PATH = "/api/v1/kits/:id/products"
CREATE_KIT_PATH = "/api/v1/kits"
